/*
 *    GeoTools - The Open Source Java GIS Toolkit
 *    http://geotools.org
 * 
 *    (C) 2002-2008, Open Source Geospatial Foundation (OSGeo)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.geotoolkit.gui.swing.style;

import org.geotoolkit.gui.swing.resource.MessageBundle;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JRadioButton;
import javax.swing.JSeparator;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import org.geotoolkit.map.MapLayer;
import org.jdesktop.swingx.JXTitledSeparator;
import org.opengis.style.ChannelSelection;
import org.opengis.style.SelectedChannelType;

/**
 * Channel selection panel
 * 
 * @author  Johann Sorel
 */
public class JChannelSelectionPane extends StyleElementEditor<ChannelSelection>{

    private MapLayer layer = null;
    private ChannelSelection channel = null;

    /** 
     * Creates new form JFillPanel 
     */
    public JChannelSelectionPane() {
        initComponents();
        lock();
    }

    @Override
    public void setLayer(MapLayer layer) {
        this.layer = layer;
    }

    @Override
    public MapLayer getLayer(){
        return layer;
    }
    
    @Override
    public void parse(ChannelSelection channel) {
        this.channel = channel;
        if (channel != null) {
            guiGray.parse(channel.getGrayChannel());
            SelectedChannelType[] sct = channel.getRGBChannels();
            
//            if(sct!= null && sct.length==3){
//                guiRed.setEdited(sct[0]);
//                guiGreen.setEdited(sct[1]);
//                guiBlue.setEdited(sct[2]);
//            }
        }
        
        lock();
    }

    @Override
    public ChannelSelection create() {

//        if (channel == null) {
//            channel = new ChannelSelectionImpl();
//        }

        apply();
        return channel;
    }

    public void apply() {
//        if (channel != null) {
//            if(guiChkRGB.isSelected()){
//                SelectedChannelType[] sct = new SelectedChannelType[3];
//                sct[0] = guiRed.getEdited();
//                sct[1] = guiGreen.getEdited();
//                sct[2] = guiBlue.getEdited();
//            }else{
//                channel.setGrayChannel(guiGray.getEdited());
//            }
//        }
    }
    
    private void lock(){
        boolean b = guiChkRGB.isSelected();
        
        guiRed.setEnabled(b);
        guiGreen.setEnabled(b);
        guiBlue.setEnabled(b);
        guiGray.setEnabled(!b);
        guiLblRed.setEnabled(b);
        guiLblGreen.setEnabled(b);
        guiLblBlue.setEnabled(b);
        guiLblGray.setEnabled(!b);
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group = new ButtonGroup();
        guiGray = new JSelectedChannelTypePane();
        guiRed = new JSelectedChannelTypePane();
        guiLblGray = new JXTitledSeparator();
        guiLblRed = new JXTitledSeparator();
        guiGreen = new JSelectedChannelTypePane();
        guiLblGreen = new JXTitledSeparator();
        guiLblBlue = new JXTitledSeparator();
        guiBlue = new JSelectedChannelTypePane();
        jSeparator1 = new JSeparator();
        guiChkRGB = new JRadioButton();
        guiChkGray = new JRadioButton();

        guiLblGray.setForeground(new Color(102, 102, 102));
        guiLblGray.setTitle(MessageBundle.getString("gray")); // NOI18N
        guiLblGray.setFont(guiLblGray.getFont().deriveFont(guiLblGray.getFont().getStyle() | Font.BOLD));

        guiLblRed.setForeground(new Color(204, 0, 0));
        guiLblRed.setTitle(MessageBundle.getString("red")); // NOI18N
        guiLblRed.setFont(guiLblRed.getFont().deriveFont(guiLblRed.getFont().getStyle() | Font.BOLD));

        guiLblGreen.setForeground(new Color(0, 204, 0));
        guiLblGreen.setTitle(MessageBundle.getString("green")); // NOI18N
        guiLblGreen.setFont(guiLblGreen.getFont().deriveFont(guiLblGreen.getFont().getStyle() | Font.BOLD));

        guiLblBlue.setForeground(new Color(0, 0, 204));
        guiLblBlue.setTitle(MessageBundle.getString("blue")); // NOI18N
        guiLblBlue.setFont(guiLblBlue.getFont().deriveFont(guiLblBlue.getFont().getStyle() | Font.BOLD));

        jSeparator1.setOrientation(SwingConstants.VERTICAL);

        guiChkRGB.setSelected(true);
        guiChkRGB.setText(MessageBundle.getString("rgb")); // NOI18N
        guiChkRGB.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                guiChkRGBActionPerformed(evt);
            }
        });

        guiChkGray.setText(MessageBundle.getString("single")); // NOI18N
        guiChkGray.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                guiChkGrayActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
                                .addComponent(guiLblRed, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(guiRed, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(guiLblGreen, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
                                .addComponent(guiLblBlue, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(guiGreen, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addComponent(guiBlue, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 7, GroupLayout.PREFERRED_SIZE))
                    .addComponent(guiChkRGB))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(guiChkGray)
                    .addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
                        .addComponent(guiLblGray, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guiGray, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        );

        layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {guiBlue, guiGray, guiGreen, guiLblBlue, guiLblGray, guiLblGreen, guiLblRed, guiRed});

        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(guiChkGray)
                    .addComponent(guiChkRGB))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
                    .addComponent(jSeparator1, Alignment.LEADING)
                    .addGroup(Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(guiLblRed, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(guiRed, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(guiLblGreen, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(guiGreen, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(guiLblBlue, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(guiBlue, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(guiLblGray, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(guiGray, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

private void guiChkGrayActionPerformed(ActionEvent evt) {//GEN-FIRST:event_guiChkGrayActionPerformed
    lock();
}//GEN-LAST:event_guiChkGrayActionPerformed

private void guiChkRGBActionPerformed(ActionEvent evt) {//GEN-FIRST:event_guiChkRGBActionPerformed
    lock();
}//GEN-LAST:event_guiChkRGBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonGroup group;
    private JSelectedChannelTypePane guiBlue;
    private JRadioButton guiChkGray;
    private JRadioButton guiChkRGB;
    private JSelectedChannelTypePane guiGray;
    private JSelectedChannelTypePane guiGreen;
    private JXTitledSeparator guiLblBlue;
    private JXTitledSeparator guiLblGray;
    private JXTitledSeparator guiLblGreen;
    private JXTitledSeparator guiLblRed;
    private JSelectedChannelTypePane guiRed;
    private JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
