/*
 *    Geotoolkit - An Open Source Java GIS Toolkit
 *    http://www.geotoolkit.org
 *
 *    (C) 2008 - 2009, Johann Sorel
 *    (C) 2012 Geomatys
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.geotoolkit.gui.swing.style;

import java.awt.Color;
import java.awt.Component;
import javax.swing.DefaultBoundedRangeModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import org.geotoolkit.gui.swing.resource.MessageBundle;

/**
 * ColorChooser with alpha
 * 
 * @author Fabien Rétif (Geomatys)
 * @module pending
 */
public class JColorPane extends javax.swing.JPanel {

    /** Creates new form JColorPane and set range of opacity */
    public JColorPane(Color c) {
        initComponents();
        setColor(c);
        guiOpacitySpinner.setModel(new SpinnerNumberModel(100, 0, 100, 1));
        guiOpacity.setModel(new DefaultBoundedRangeModel(100,1,0,100));
        guiOpacity.setMinorTickSpacing(0);
        guiOpacity.setMajorTickSpacing(100);
        
    }
    
    public JColorPane() {
        initComponents();
        setColor(Color.red);
    }
    
    public Color getColor(){
        Color c = this.guiColor.getColor();
        int alpha = this.guiOpacity.getValue();
        c = new Color(c.getRed(), c.getGreen(), c.getBlue(),alpha);
        return c;
    }
    
    public void setColor(Color c){
        if(c == null){
            c = Color.WHITE;
        }
        this.guiColor.setColor(c);
        this.guiOpacity.setValue(c.getAlpha());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        guiColor = new javax.swing.JColorChooser();
        guiOpacity = new javax.swing.JSlider();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        guiOpacitySpinner = new javax.swing.JSpinner();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        guiColor.setBackground(new java.awt.Color(195, 191, 191));

        guiOpacity.setMajorTickSpacing(100);
        guiOpacity.setPaintLabels(true);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, guiOpacitySpinner, org.jdesktop.beansbinding.ELProperty.create("${value}"), guiOpacity, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        jLabel1.setText(MessageBundle.getString("opacity")); // NOI18N

        guiOpacitySpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, guiOpacity, org.jdesktop.beansbinding.ELProperty.create("${value}"), guiOpacitySpinner, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guiColor, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiOpacity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiOpacitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guiColor, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guiOpacity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(guiOpacitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser guiColor;
    private javax.swing.JSlider guiOpacity;
    private javax.swing.JSpinner guiOpacitySpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables


    public static Color showDialog(Component component, String title, Color initialColor) {
        final JColorPane pane = new JColorPane(initialColor != null? initialColor : Color.white);
        JOptionPane.showMessageDialog(component,pane,title,JOptionPane.PLAIN_MESSAGE);
        return pane.getColor();
    }
    
}
