/*
 *    Geotoolkit - An Open Source Java GIS Toolkit
 *    http://www.geotoolkit.org
 *
 *    (C) 2007 - 2008, Open Source Geospatial Foundation (OSGeo)
 *    (C) 2008 - 2009, Johann Sorel
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.geotoolkit.gui.swing.style;

import java.util.ResourceBundle;
import org.geotoolkit.gui.swing.resource.MessageBundle;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import org.geotoolkit.gui.swing.style.StyleElementEditor;
import org.geotoolkit.map.MapLayer;
import org.opengis.style.Fill;

/**
 * Fill panel
 * 
 * @author  Johann Sorel
 */
public class JFillPane extends StyleElementEditor<Fill>{

    private MapLayer layer = null;
    private Fill fill = null;

    /** 
     * Creates new form JFillPanel 
     */
    public JFillPane() {
        initComponents();
        butFill.setEnabled(false);
        guiAlpha.setModel(1d, 0d, 1d, 0.1d);
    }

    /**
     * {@inheritDoc }
     */
    @Override
    public void setLayer(MapLayer layer) {
        this.layer = layer;
        guiColor.setLayer(layer);
        guiAlpha.setLayer(layer);
    }

    /**
     * {@inheritDoc }
     */
    @Override
    public MapLayer getLayer(){
        return layer;
    }
    
    /**
     * {@inheritDoc }
     */
    @Override
    public void parse(Fill fill) {
        this.fill = fill;
        if (fill != null) {
            guiColor.parse(fill.getColor());
            guiAlpha.parse(fill.getOpacity());
            //handle by a button
            //fill.getGraphicFill();
        }
    }

    /**
     * {@inheritDoc }
     */
    @Override
    public Fill create() {
        return getStyleFactory().fill(
                guiColor.create(), 
                guiAlpha.create());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butFill = new JButton();
        jLabel3 = new JLabel();
        lbl2 = new JLabel();
        lbl_color1 = new JLabel();
        guiColor = new JColorExpressionPane();
        guiAlpha = new JNumberExpressionPane();

        setOpaque(false);

        ResourceBundle bundle = ResourceBundle.getBundle("org/geotoolkit/gui/swing/resource/Bundle"); // NOI18N
        butFill.setText(bundle.getString("fill")); // NOI18N
        butFill.setBorderPainted(false);



        butFill.setPreferredSize(new Dimension(49, 22));
        butFill.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                butFillActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel3.setText(MessageBundle.getString("graphic")); // NOI18N
        lbl2.setHorizontalAlignment(SwingConstants.RIGHT);
        lbl2.setText(MessageBundle.getString("opacity")); // NOI18N
        lbl_color1.setHorizontalAlignment(SwingConstants.RIGHT);
        lbl_color1.setText(MessageBundle.getString("color")); // NOI18N
        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_color1)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(guiColor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl2)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(guiAlpha, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(butFill, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {jLabel3, lbl2, lbl_color1});

        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(Alignment.TRAILING)
                    .addComponent(lbl_color1)
                    .addComponent(guiColor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(Alignment.LEADING, false)
                    .addComponent(lbl2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guiAlpha, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(butFill, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void butFillActionPerformed(ActionEvent evt) {//GEN-FIRST:event_butFillActionPerformed
//        JDialog dia = new JDialog();
//
//        JGraphicPane pane = new JGraphicPane();
//        pane.setLayer(layer);
//
//        if (fill != null) {
//            pane.parse(fill.getGraphicFill());
//        }
//
//        dia.setContentPane(pane);
//        dia.pack();
//        dia.setLocationRelativeTo(butFill);
//        dia.setModal(true);
//        dia.setVisible(true);
//
//        fill = new StyleBuilder().createFill();
//        
//        fill.setGraphicFill(pane.getEdited());
    }//GEN-LAST:event_butFillActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton butFill;
    private JNumberExpressionPane guiAlpha;
    private JColorExpressionPane guiColor;
    private JLabel jLabel3;
    private JLabel lbl2;
    private JLabel lbl_color1;
    // End of variables declaration//GEN-END:variables
}
