/*
/*
 *    GeoTools - The Open Source Java GIS Toolkit
 *    http://geotools.org
 * 
 *    (C) 2002-2008, Open Source Geospatial Foundation (OSGeo)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.geotoolkit.gui.swing.style;

import java.awt.Component;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JToggleButton;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import org.geotoolkit.gui.swing.resource.IconBundle;
import org.geotoolkit.gui.swing.style.StyleElementEditor;
import org.geotoolkit.map.MapLayer;
import org.geotoolkit.style.StyleConstants;
import org.opengis.filter.expression.Expression;

/**
 *
 * @author Johann Sorel (Puzzle-GIS)
 */
public class JLineJoinExpressionPane extends StyleElementEditor<Expression>{

    private static final ImageIcon ICON_JOIN_ROUND = IconBundle.getInstance().getIcon("16_linejoin_round");
    private static final ImageIcon ICON_JOIN_MITRE = IconBundle.getInstance().getIcon("16_linejoin_mitre");
    private static final ImageIcon ICON_JOIN_BEVEL = IconBundle.getInstance().getIcon("16_linejoin_bevel");

    /** Creates new form JColorExpressionPane */
    public JLineJoinExpressionPane() {
        initComponents();
        guiBevel.setIcon(ICON_JOIN_BEVEL);
        guiMiter.setIcon(ICON_JOIN_MITRE);
        guiRound.setIcon(ICON_JOIN_ROUND);
    }

    @Override
    public void setLayer(MapLayer layer) {
        super.setLayer(layer);
        guiSpecial.setLayer(layer);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        joinGroup = new ButtonGroup();
        guiSpecial = new JSpecialExpressionButton();
        guiRound = new JToggleButton();
        guiMiter = new JToggleButton();
        guiBevel = new JToggleButton();

        setOpaque(false);

        guiSpecial.addPropertyChangeListener(new PropertyChangeListener() {
            public void propertyChange(PropertyChangeEvent evt) {
                guiSpecialPropertyChange(evt);
            }
        });

        joinGroup.add(guiRound);
        guiRound.setSelected(true);
        guiRound.setBorderPainted(false);
        guiRound.setIconTextGap(0);
        guiRound.setMargin(new Insets(2, 2, 2, 2));
        guiRound.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                guiRoundActionPerformed(evt);
            }
        });

        joinGroup.add(guiMiter);
        guiMiter.setBorderPainted(false);
        guiMiter.setIconTextGap(0);
        guiMiter.setMargin(new Insets(2, 2, 2, 2));
        guiMiter.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                guiMiterActionPerformed(evt);
            }
        });

        joinGroup.add(guiBevel);
        guiBevel.setBorderPainted(false);
        guiBevel.setIconTextGap(0);
        guiBevel.setMargin(new Insets(2, 2, 2, 2));
        guiBevel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                guiBevelActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(guiRound)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(guiMiter)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(guiBevel)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(guiSpecial, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {guiBevel, guiMiter, guiRound, guiSpecial});

        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
                .addComponent(guiSpecial, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
                .addGroup(Alignment.LEADING, layout.createParallelGroup(Alignment.TRAILING, false)
                    .addComponent(guiRound, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guiMiter, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guiBevel, Alignment.LEADING)))
        );

        layout.linkSize(SwingConstants.VERTICAL, new Component[] {guiBevel, guiMiter, guiRound, guiSpecial});

    }// </editor-fold>//GEN-END:initComponents

private void guiSpecialPropertyChange(PropertyChangeEvent evt) {//GEN-FIRST:event_guiSpecialPropertyChange
    if(evt.getPropertyName().equals(JSpecialExpressionButton.EXPRESSION_PROPERTY)) {
        parse(guiSpecial.get());
    }
}//GEN-LAST:event_guiSpecialPropertyChange

private void guiRoundActionPerformed(ActionEvent evt) {//GEN-FIRST:event_guiRoundActionPerformed
    parse(StyleConstants.STROKE_JOIN_ROUND);
}//GEN-LAST:event_guiRoundActionPerformed

private void guiMiterActionPerformed(ActionEvent evt) {//GEN-FIRST:event_guiMiterActionPerformed
    parse(StyleConstants.STROKE_JOIN_MITRE);
}//GEN-LAST:event_guiMiterActionPerformed

private void guiBevelActionPerformed(ActionEvent evt) {//GEN-FIRST:event_guiBevelActionPerformed
    parse(StyleConstants.STROKE_JOIN_BEVEL);
}//GEN-LAST:event_guiBevelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JToggleButton guiBevel;
    private JToggleButton guiMiter;
    private JToggleButton guiRound;
    private JSpecialExpressionButton guiSpecial;
    private ButtonGroup joinGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public void parse(Expression target) {
        if(target != null){
            if(StyleConstants.STROKE_JOIN_BEVEL.equals(target)){
                guiSpecial.parse(null);
                guiBevel.setSelected(true);
            }else if(StyleConstants.STROKE_JOIN_ROUND.equals(target)){
                guiSpecial.parse(null);
                guiRound.setSelected(true);
            }else if(StyleConstants.STROKE_JOIN_MITRE.equals(target)){
                guiSpecial.parse(null);
                guiMiter.setSelected(true);
            }else{
                guiSpecial.parse(target);
                joinGroup.clearSelection();
            }
        }else{
            guiSpecial.parse(null);
            guiBevel.setSelected(true);
            guiRound.setSelected(false);
            guiMiter.setSelected(false);
        }
    }

    @Override
    public Expression create() {
        final Expression special = guiSpecial.get();
        if(special != null){
            return special;
        }else{
            if(guiRound.isSelected())       return StyleConstants.STROKE_JOIN_ROUND;
            else if(guiMiter.isSelected()) return StyleConstants.STROKE_JOIN_MITRE;
            else                            return StyleConstants.STROKE_JOIN_BEVEL;
        }
    }

}
