/*
 *    Geotoolkit - An Open Source Java GIS Toolkit
 *    http://www.geotoolkit.org
 *
 *    (C) 2007 - 2008, Open Source Geospatial Foundation (OSGeo)
 *    (C) 2008 - 2009, Johann Sorel
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.geotoolkit.gui.swing.style;

import org.geotoolkit.gui.swing.resource.MessageBundle;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingConstants;
import org.geotools.filter.text.cql2.CQL;
import org.geotools.filter.text.cql2.CQLException;
import org.geotoolkit.gui.swing.propertyedit.filterproperty.JCQLPropertyPanel;
import org.geotoolkit.map.MapLayer;
import org.geotoolkit.style.MutableRule;
import org.jdesktop.swingx.JXTitledPanel;
import org.opengis.filter.Filter;

/**
 *
 * @author Johann Sorel (Puzzle-GIS)
 */
public class JRulePane extends StyleElementEditor<MutableRule> {

    private MutableRule rule = null;
    
    private MapLayer layer = null;
    

    /** Creates new form JRulePanel */
    public JRulePane() {
        initComponents();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXTitledPanel1 = new JXTitledPanel();
        but_edit = new JButton();
        jScrollPane1 = new JScrollPane();
        jtp_filter = new JTextPane();
        jLabel3 = new JLabel();
        jsp_minscale = new JSpinner();
        jLabel4 = new JLabel();
        jsp_maxscale = new JSpinner();
        jck_else = new JCheckBox();
        jXTitledPanel2 = new JXTitledPanel();
        jLabel1 = new JLabel();
        jtf_title = new JTextField();
        jLabel2 = new JLabel();
        jtf_name = new JTextField();
        jLabel6 = new JLabel();
        jtf_abstract = new JTextField();

        setOpaque(false);


        jXTitledPanel1.setBorder(BorderFactory.createEtchedBorder());
        jXTitledPanel1.setTitle(MessageBundle.getString("filter2")); // NOI18N
        but_edit.setText(MessageBundle.getString("edit")); // NOI18N
        but_edit.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                but_editActionPerformed(evt);
            }
        });

        jtp_filter.setEditable(false);
        jScrollPane1.setViewportView(jtp_filter);



        jLabel3.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel3.setText(MessageBundle.getString("minscale")); // NOI18N
        jsp_minscale.setModel(new SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1000.0d)));

        jLabel4.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel4.setText(MessageBundle.getString("maxscale")); // NOI18N
        jsp_maxscale.setModel(new SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1000.0d)));

        jck_else.setText(MessageBundle.getString("else_filter")); // NOI18N
        jck_else.setOpaque(false);

        GroupLayout jXTitledPanel1Layout = new GroupLayout(jXTitledPanel1.getContentContainer());
        jXTitledPanel1.getContentContainer().setLayout(jXTitledPanel1Layout);




        jXTitledPanel1Layout.setHorizontalGroup(
            jXTitledPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel1Layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(jXTitledPanel1Layout.createParallelGroup(Alignment.LEADING, false)
                        .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(jsp_minscale, GroupLayout.PREFERRED_SIZE, 146, GroupLayout.PREFERRED_SIZE))
                        .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(jsp_maxscale)))
                    .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                        .addComponent(but_edit)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                    .addComponent(jck_else))
                .addContainerGap())
        );

        jXTitledPanel1Layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {jLabel3, jLabel4});

        jXTitledPanel1Layout.setVerticalGroup(
            jXTitledPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jck_else)
                .addGap(4, 4, 4)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jsp_minscale, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jsp_maxscale, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(but_edit)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jXTitledPanel2.setBorder(BorderFactory.createEtchedBorder());
        jXTitledPanel2.setTitle(MessageBundle.getString("general")); // NOI18N
        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | Font.BOLD));
        jLabel1.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel1.setText(MessageBundle.getString("title")); // NOI18N
        jLabel2.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel2.setText(MessageBundle.getString("name")); // NOI18N
        jLabel6.setText(MessageBundle.getString("abstract")); // NOI18N
        GroupLayout jXTitledPanel2Layout = new GroupLayout(jXTitledPanel2.getContentContainer());
        jXTitledPanel2.getContentContainer().setLayout(jXTitledPanel2Layout);
        jXTitledPanel2Layout.setHorizontalGroup(
            jXTitledPanel2Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jXTitledPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel2Layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(jXTitledPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(jtf_name, GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                    .addGroup(jXTitledPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(jtf_title, GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                    .addGroup(Alignment.TRAILING, jXTitledPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(jtf_abstract, GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jXTitledPanel2Layout.setVerticalGroup(
            jXTitledPanel2Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jXTitledPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel2Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_name, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel2Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtf_title, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel2Layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtf_abstract, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addComponent(jXTitledPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jXTitledPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXTitledPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jXTitledPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void but_editActionPerformed(ActionEvent evt) {//GEN-FIRST:event_but_editActionPerformed
        if(rule == null){
            rule = getStyleFactory().rule();
        }
        
        final JDialog dialog = new JDialog();
        final JCQLPropertyPanel cql = new JCQLPropertyPanel();
        if(rule.getFilter() != null){
            cql.setFilter(rule.getFilter());
        }

        dialog.setContentPane(cql);
        dialog.setModal(true);
        dialog.pack();
        dialog.setLocationRelativeTo((JButton) evt.getSource());
        dialog.setVisible(true);

        rule.setFilter(cql.getFilter());
                
    }//GEN-LAST:event_but_editActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton but_edit;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel6;
    private JScrollPane jScrollPane1;
    private JXTitledPanel jXTitledPanel1;
    private JXTitledPanel jXTitledPanel2;
    private JCheckBox jck_else;
    private JSpinner jsp_maxscale;
    private JSpinner jsp_minscale;
    private JTextField jtf_abstract;
    private JTextField jtf_name;
    private JTextField jtf_title;
    private JTextPane jtp_filter;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setLayer(MapLayer layer) {
        this.layer = layer;
    }

    @Override
    public MapLayer getLayer() {
        return layer;
    }

    @Override
    public void parse(MutableRule target) {
        this.rule = target;
        if (rule != null) {
            jtf_name.setText(rule.getName());
            jtf_title.setText(rule.getDescription().getTitle().toString());
            jtf_abstract.setText(rule.getDescription().getAbstract().toString());
            jck_else.setSelected(rule.isElseFilter());
            
            jsp_maxscale.setValue(rule.getMaxScaleDenominator());
            jsp_minscale.setValue(rule.getMinScaleDenominator());
            
            if (rule.getFilter() != null) {
                try {
                    jtp_filter.setText(CQL.toCQL(rule.getFilter()));
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }

    @Override
    public MutableRule create() {
        if(rule == null){
            rule = getStyleFactory().rule();
        }
        
        rule.setName(jtf_name.getText());
        rule.setDescription(getStyleFactory().description(
                jtf_title.getText(), 
                jtf_abstract.getText()));
        rule.setMinScaleDenominator( (Double)jsp_minscale.getValue() );
        rule.setMaxScaleDenominator( (Double)jsp_maxscale.getValue() );
        rule.setElseFilter(jck_else.isSelected());

        String str = jtp_filter.getText().trim();

        if(!str.isEmpty()){
            try {
                Filter f = CQL.toFilter(jtp_filter.getText());
                rule.setFilter(f);
            } catch (CQLException ex) {
                System.out.println("Invalide CQL expression : ignore it");
            }
        }
        
        return rule;
    }

    @Override
    public void apply() {
        create();
    }
    
}
