/*
 *    Geotoolkit - An Open Source Java GIS Toolkit
 *    http://www.geotoolkit.org
 *
 *    (C) 2007 - 2008, Open Source Geospatial Foundation (OSGeo)
 *    (C) 2008 - 2009, Johann Sorel
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.geotoolkit.gui.swing.style;

import org.geotoolkit.gui.swing.resource.MessageBundle;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JToolBar;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import org.geotoolkit.gui.swing.resource.IconBundle;

/**
 * Simple dialog
 * 
 * @author Johann Sorel
 * @module pending
 */
public class JSimpleDialog extends javax.swing.JDialog {

    private static final ImageIcon ICO_CLOSE = IconBundle.getIcon("16_close");
    
    /** Creates new form JSimpleDialog */
    public JSimpleDialog(final java.awt.Frame parent, final boolean modal,final Component child) {
        super(parent, modal);
        initComponents();
        
        JToolBar guiBar = new JToolBar();
        guiBar.setLayout(new FlowLayout(FlowLayout.RIGHT));
        guiBar.add(guiClose);
        guiBar.setFloatable(false);
        
        JScrollPane jsp = new JScrollPane(child);
        
        add(BorderLayout.CENTER,jsp);
        add(BorderLayout.SOUTH,guiBar);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guiClose = new JButton();

        guiClose.setIcon(ICO_CLOSE);
        guiClose.setText(MessageBundle.getString("property_close")); // NOI18N
        guiClose.setFocusable(false);
        guiClose.setHorizontalTextPosition(SwingConstants.CENTER);
        guiClose.setVerticalTextPosition(SwingConstants.BOTTOM);
        guiClose.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                guiCloseActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void guiCloseActionPerformed(final ActionEvent evt) {//GEN-FIRST:event_guiCloseActionPerformed
    
    this.dispose();
}//GEN-LAST:event_guiCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton guiClose;
    // End of variables declaration//GEN-END:variables

}
