/*
 *    GeoTools - The Open Source Java GIS Toolkit
 *    http://geotools.org
 * 
 *    (C) 2002-2008, Open Source Geospatial Foundation (OSGeo)
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.geotoolkit.gui.swing.style;

import org.geotoolkit.gui.swing.resource.MessageBundle;
import java.awt.Component;
import java.awt.FlowLayout;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import org.geotoolkit.map.MapLayer;
import org.geotoolkit.style.StyleConstants;

import org.jdesktop.swingx.JXTitledPanel;
import org.opengis.style.TextSymbolizer;

/**
 * Text Symbolizer edition panel
 * 
 * @author Johann Sorel
 */
public class JTextSymbolizerPane extends StyleElementEditor<TextSymbolizer> {
    
    private MapLayer layer = null;

    /** Creates new form JTextSymbolizer */
    public JTextSymbolizerPane() {
        initComponents();
            }

    /**
     * {@inheritDoc }
     */
    @Override
    public void setLayer(MapLayer layer) {
        this.layer = layer;
        guiFill.setLayer(layer);
        guiHalo.setLayer(layer);
        guiFont.setLayer(layer);
        guiGeom.setLayer(layer);
        guiLabel.setLayer(layer);
        guiPlacement.setLayer(layer);
            }

    /**
     * {@inheritDoc }
     */
    @Override
    public MapLayer getLayer() {
        return layer;
            }

    /**
     * {@inheritDoc }
     */
    @Override
    public TextSymbolizer create() {
        return getStyleFactory().textSymbolizer(
                "TextSymbolizer",
                guiGeom.getGeom(),
                StyleConstants.DEFAULT_DESCRIPTION,
                guiUOM.create(),
                guiLabel.create(), 
                guiFont.create(), 
                guiPlacement.create(), 
                guiHalo.create(), 
                guiFill.create() );
    }

    /**
     * {@inheritDoc }
     */
    @Override
    public void parse(TextSymbolizer symbol) {
        if (symbol != null) {
            guiFill.parse(symbol.getFill());
            guiLabel.parse(symbol.getLabel());
            guiGeom.setGeom(symbol.getGeometryPropertyName());
            guiFont.parse(symbol.getFont());
            guiHalo.parse(symbol.getHalo());
            guiPlacement.parse(symbol.getLabelPlacement());        
    }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXTitledPanel2 = new JXTitledPanel();
        guiFill = new JFillPane();
        jXTitledPanel3 = new JXTitledPanel();
        guiHalo = new JHaloPane();
        jXTitledPanel4 = new JXTitledPanel();
        guiFont = new JFontPane();
        jXTitledPanel5 = new JXTitledPanel();
        guiPlacement = new JLabelPlacementPane();
        jXTitledPanel1 = new JXTitledPanel();
        guiGeom = new JGeomPane();
        guiUOM = new JUOMPane();
        jLabel1 = new JLabel();
        guiLabel = new JTextExpressionPane();

        setOpaque(false);

        jXTitledPanel2.setBorder(BorderFactory.createEtchedBorder());
        jXTitledPanel2.setTitle(MessageBundle.getString("fill")); // NOI18N
        jXTitledPanel2.getContentContainer().setLayout(new FlowLayout(FlowLayout.LEFT, 10, 5));
        jXTitledPanel2.getContentContainer().add(guiFill);

        jXTitledPanel3.setBorder(BorderFactory.createEtchedBorder());
        jXTitledPanel3.setTitle(MessageBundle.getString("halo")); // NOI18N
        jXTitledPanel3.getContentContainer().setLayout(new FlowLayout(FlowLayout.LEFT, 10, 5));
        jXTitledPanel3.getContentContainer().add(guiHalo);

        jXTitledPanel4.setBorder(BorderFactory.createEtchedBorder());
        jXTitledPanel4.setTitle(MessageBundle.getString("fonts")); // NOI18N
        jXTitledPanel4.getContentContainer().setLayout(new FlowLayout(FlowLayout.LEFT, 10, 5));
        jXTitledPanel4.getContentContainer().add(guiFont);

        jXTitledPanel5.setBorder(BorderFactory.createEtchedBorder());
        jXTitledPanel5.setTitle(MessageBundle.getString("placement")); // NOI18N
        jXTitledPanel5.getContentContainer().setLayout(new FlowLayout(FlowLayout.LEFT, 10, 5));
        jXTitledPanel5.getContentContainer().add(guiPlacement);



        jXTitledPanel1.setBorder(BorderFactory.createEtchedBorder());
        jXTitledPanel1.setTitle(MessageBundle.getString("general")); // NOI18N
        jLabel1.setText(MessageBundle.getString("label")); // NOI18N
        GroupLayout jXTitledPanel1Layout = new GroupLayout(jXTitledPanel1.getContentContainer());
        jXTitledPanel1.getContentContainer().setLayout(jXTitledPanel1Layout);
        jXTitledPanel1Layout.setHorizontalGroup(
            jXTitledPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel1Layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(jXTitledPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
                        .addComponent(guiUOM, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guiGeom, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(guiLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jXTitledPanel1Layout.setVerticalGroup(
            jXTitledPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guiGeom, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(guiUOM, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(Alignment.TRAILING)
                    .addComponent(guiLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jXTitledPanel1Layout.linkSize(SwingConstants.VERTICAL, new Component[] {guiLabel, jLabel1});

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addComponent(jXTitledPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jXTitledPanel4, GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
            .addComponent(jXTitledPanel2, GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
            .addComponent(jXTitledPanel3, GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
            .addComponent(jXTitledPanel5, GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXTitledPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jXTitledPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jXTitledPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jXTitledPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jXTitledPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JFillPane guiFill;
    private JFontPane guiFont;
    private JGeomPane guiGeom;
    private JHaloPane guiHalo;
    private JTextExpressionPane guiLabel;
    private JLabelPlacementPane guiPlacement;
    private JUOMPane guiUOM;
    private JLabel jLabel1;
    private JXTitledPanel jXTitledPanel1;
    private JXTitledPanel jXTitledPanel2;
    private JXTitledPanel jXTitledPanel3;
    private JXTitledPanel jXTitledPanel4;
    private JXTitledPanel jXTitledPanel5;
    // End of variables declaration//GEN-END:variables

}
