# IMPORTANT notes:
# 1. Use a global maven cache to avoid downloading released dependencies everytime
# 2. sis-migration disabled (see comments in .gitlab/CI/build.yml file)
# 3. Release stage not ready yet. Only a manual maven artifact is available for now. More details about release work in
#    "TODO" comment in related file.
variables:
  MAVEN_LOCAL: ".m2_local"
  MAVEN_OPTS: "-Dmaven.repo.local=$MAVEN_LOCAL -Djava.awt.headless=true"
  SONAR_HOST_URL: "https://sonar.geomatys.com"
  DEPLOY_SERVER: "releases::https://nexus.geomatys.com/repository/releases/"
  TAG_VERSION:
    description: "When filled, a tag with this value will be created on the project"

workflow:
  rules:
    - if: ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_TAG || $TAG_VERSION)

# Cache dependencies globally. Project snapshot are removed with below after script to avoid caching nightly artifact.
cache: &global_cache
  policy: pull
  key: GEOTK_MVN_CACHE
  paths:
    - "$MAVEN_LOCAL"

stages:
  - build
  - quality
  - release
  - publish

image: maven:3.9.9-eclipse-temurin-23

# Force removing artifacts installed by local jobs, to avoid cache corruption with snapshots.
after_script:
  - mvn build-helper:remove-project-artifact > /dev/null && echo "Successfully removed project artifacts from cache"

# Hidden job to be inherited (extends) by build job
.update-cache:
  cache:
    <<: *global_cache
    policy: pull-push

include:
  - '.gitlab/CI/build.yml'
  - '.gitlab/CI/quality.yml'
  - '.gitlab/CI/release.yml'
