/*
 *    Geotoolkit - An Open Source Java GIS Toolkit
 *    http://www.geotoolkit.org
 *
 *    (C) 2007 - 2008, Open Source Geospatial Foundation (OSGeo)
 *    (C) 2008 - 2010, Johann Sorel
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.geotoolkit.gui.swing.propertyedit.styleproperty;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreePath;
import org.geotoolkit.gui.swing.propertyedit.PropertyPane;
import org.geotoolkit.gui.swing.resource.IconBundle;
import org.geotoolkit.gui.swing.resource.MessageBundle;
import org.geotoolkit.gui.swing.style.JStyleTree;
import org.geotoolkit.gui.swing.style.StyleElementEditor;
import org.geotoolkit.map.MapLayer;
import org.geotoolkit.style.MutableRule;
import org.geotoolkit.style.MutableStyle;
import org.opengis.style.Symbolizer;

/**
 * @author Johann Sorel (Puzzle-GIS)
 * @module pending
 */
public class JAdvancedStylePanel extends StyleElementEditor implements PropertyPane {

    private MapLayer layer = null;
    private Object style = null;
    private StyleElementEditor editor = null;
    private final TreeSelectionListener listener = new TreeSelectionListener() {

        @Override
        public void valueChanged(TreeSelectionEvent e) {
            final TreePath path = e.getNewLeadSelectionPath();

            //we validate the previous edition pane
            applyEditor(e.getOldLeadSelectionPath());

            pan_info.removeAll();
            
            if (path != null) {
                final Object val = ((DefaultMutableTreeNode) path.getLastPathComponent()).getUserObject();
                editor = StyleElementEditor.findEditor(val);
                if(editor != null){
                    editor.setLayer(getLayer());
                    editor.parse(val);
                    pan_info.add(editor);
                }                
            }
            
            pan_info.revalidate();
            pan_info.repaint();
        }
    };

    /** Creates new form JAdvancedStylePanel */
    public JAdvancedStylePanel() {
        super(Object.class);
        initComponents();
        tree.addTreeSelectionListener(listener);
    }

    private void applyEditor(final TreePath oldPath){
        if(editor == null) return;

        //create implies a call to apply if a style element is present
        final Object obj = editor.create();
        editor.parse(obj);
        
        if(obj instanceof Symbolizer){
            //in case of a symbolizer we must update it.
            if(oldPath != null && oldPath.getLastPathComponent() != null){
                final Symbolizer symbol = (Symbolizer) ((DefaultMutableTreeNode)oldPath.getLastPathComponent()).getUserObject();

                if(!symbol.equals(obj)){
                    //new symbol created is different, update in the rule
                    final MutableRule rule = (MutableRule) ((DefaultMutableTreeNode)oldPath.getParentPath().getLastPathComponent()).getUserObject();

                    final int index = rule.symbolizers().indexOf(symbol);
                    if(index >= 0){
                        rule.symbolizers().set(index, (Symbolizer) obj);
                    }
                }
            }
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new JSplitPane();
        jsp2 = new JScrollPane();
        tree = new JStyleTree();
        jScrollPane1 = new JScrollPane();
        pan_info = new JPanel();

        setLayout(new BorderLayout());

        jSplitPane1.setDividerLocation(220);
        jSplitPane1.setDividerSize(4);

        jsp2.setViewportView(tree);

        jSplitPane1.setLeftComponent(jsp2);

        pan_info.setLayout(new GridLayout(1, 1));
        jScrollPane1.setViewportView(pan_info);

        jSplitPane1.setRightComponent(jScrollPane1);

        add(jSplitPane1, BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    @Override
    public boolean canHandle(Object target) {
        return target instanceof MapLayer;
    }
    
    @Override
    public void apply() {

        applyEditor(tree.getSelectionModel().getSelectionPath());

        style = tree.getStyleElement();

        if (layer != null && style instanceof MutableStyle && style != layer.getStyle()) {
            layer.setStyle((MutableStyle)style);
        }
    }

    @Override
    public void setLayer(final MapLayer layer) {
        this.layer = layer;
    }

    @Override
    public MapLayer getLayer() {
        return layer;
    }

    @Override
    public void parse(final Object style) {
        this.style = style;
        parse();
    }

    @Override
    public Object create() {
        style = tree.getStyleElement();
        apply();
        return style;
    }

    private void parse() {
        tree.setStyleElement(style);
    }

    @Override
    public ImageIcon getIcon() {
        return IconBundle.getIcon("16_advanced_style");
    }
    
    @Override
    public Image getPreview() {
        return null;
    }

    @Override
    public String getTitle() {
        return MessageBundle.getString("advanced");
    }

    @Override
    public void setTarget(final Object layer) {

        if (layer instanceof MapLayer) {
            setLayer((MapLayer) layer);
            parse(this.layer.getStyle());
        }
    }

    @Override
    public void reset() {
        parse();
    }

    @Override
    public String getToolTip() {
        return "";
    }

    @Override
    public Component getComponent() {
        return this;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    JScrollPane jScrollPane1;
    JSplitPane jSplitPane1;
    JScrollPane jsp2;
    JPanel pan_info;
    JStyleTree tree;
    // End of variables declaration//GEN-END:variables


}
