/*
 *    Geotoolkit - An Open Source Java GIS Toolkit
 *    http://www.geotoolkit.org
 *
 *    (C) 2009 Geomatys
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */

package org.geotoolkit.gui.swing.propertyedit.styleproperty;

import java.awt.Color;
import org.geotoolkit.gui.swing.resource.MessageBundle;
import org.jdesktop.swingx.decorator.Highlighter;
import org.jdesktop.swingx.decorator.HighlighterFactory;
import org.jfree.chart.ChartPanel;

/**
 *
 * @author Johann Sorel (Geomatys)
 */
public class JAnalizePanel extends javax.swing.JPanel {

    private final Analyze analyze;

    /** Creates new form JAnalizePanel */
    public JAnalizePanel(Analyze analyze) {
        this.analyze = analyze;
        initComponents();

        guiTable.setTableHeader(null);
        guiTable.setShowGrid(false, false);
        guiTable.setHighlighters(new Highlighter[]{HighlighterFactory.createAlternateStriping(Color.white, HighlighterFactory.QUICKSILVER, 1)});
        guiTable.setModel(analyze);

        guiChart.add(new ChartPanel(analyze.getChart()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        guiLblCount = new javax.swing.JLabel();
        guiLblMinimum = new javax.swing.JLabel();
        guiLblMaximum = new javax.swing.JLabel();
        guiLblSum = new javax.swing.JLabel();
        guiCount = new javax.swing.JLabel();
        guiMinimum = new javax.swing.JLabel();
        guiMaximum = new javax.swing.JLabel();
        guiSum = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        guiLblMean = new javax.swing.JLabel();
        guiLblMedian = new javax.swing.JLabel();
        guiLblDeviation = new javax.swing.JLabel();
        guiMean = new javax.swing.JLabel();
        guiMedian = new javax.swing.JLabel();
        guiDeviation = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        guiLblMethod = new javax.swing.JLabel();
        guiLblClasses = new javax.swing.JLabel();
        guiMethod = new javax.swing.JComboBox();
        guiClasses = new javax.swing.JSpinner();
        jSplitPane1 = new javax.swing.JSplitPane();
        guiChart = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        guiTable = new org.jdesktop.swingx.JXTable();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        guiLblCount.setText(MessageBundle.getString("count")); // NOI18N

        guiLblMinimum.setText(MessageBundle.getString("minimum")); // NOI18N

        guiLblMaximum.setText(MessageBundle.getString("maximum")); // NOI18N

        guiLblSum.setText(MessageBundle.getString("sum")); // NOI18N

        guiCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        guiCount.setText("0");
        guiCount.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        guiMinimum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        guiMinimum.setText("0");
        guiMinimum.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        guiMaximum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        guiMaximum.setText("0");
        guiMaximum.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        guiSum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        guiSum.setText("0");
        guiSum.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        guiLblMean.setText(MessageBundle.getString("mean")); // NOI18N

        guiLblMedian.setText(MessageBundle.getString("median")); // NOI18N

        guiLblDeviation.setText(MessageBundle.getString("deviation")); // NOI18N

        guiMean.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        guiMean.setText("0");

        guiMedian.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        guiMedian.setText("0");

        guiDeviation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        guiDeviation.setText("0");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        guiLblMethod.setText(MessageBundle.getString("method")); // NOI18N

        guiLblClasses.setText(MessageBundle.getString("classes")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(guiLblMethod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(guiLblClasses)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(guiLblCount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiCount))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(guiLblMinimum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiMinimum))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(guiLblMaximum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiMaximum))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(guiLblSum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiSum)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(guiLblMean)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiMean))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(guiLblMedian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiMedian))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(guiLblDeviation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiDeviation)))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {guiClasses, guiMethod});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {guiLblClasses, guiLblMethod});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {guiLblCount, guiLblMaximum, guiLblMinimum, guiLblSum});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {guiLblDeviation, guiLblMean, guiLblMedian});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {guiCount, guiMaximum, guiMinimum, guiSum});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guiLblMethod)
                    .addComponent(guiMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guiLblClasses)
                    .addComponent(guiClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guiLblCount)
                    .addComponent(guiCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guiLblMinimum)
                    .addComponent(guiMinimum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guiLblMaximum)
                    .addComponent(guiMaximum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guiLblSum)
                    .addComponent(guiSum))
                .addContainerGap())
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guiLblMean)
                    .addComponent(guiMean))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guiLblMedian)
                    .addComponent(guiMedian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guiLblDeviation)
                    .addComponent(guiDeviation))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(225);
        jSplitPane1.setDividerSize(3);

        guiChart.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(guiChart);

        guiTable.setBorder(null);
        guiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(guiTable);

        jSplitPane1.setLeftComponent(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel guiChart;
    private javax.swing.JSpinner guiClasses;
    private javax.swing.JLabel guiCount;
    private javax.swing.JLabel guiDeviation;
    private javax.swing.JLabel guiLblClasses;
    private javax.swing.JLabel guiLblCount;
    private javax.swing.JLabel guiLblDeviation;
    private javax.swing.JLabel guiLblMaximum;
    private javax.swing.JLabel guiLblMean;
    private javax.swing.JLabel guiLblMedian;
    private javax.swing.JLabel guiLblMethod;
    private javax.swing.JLabel guiLblMinimum;
    private javax.swing.JLabel guiLblSum;
    private javax.swing.JLabel guiMaximum;
    private javax.swing.JLabel guiMean;
    private javax.swing.JLabel guiMedian;
    private javax.swing.JComboBox guiMethod;
    private javax.swing.JLabel guiMinimum;
    private javax.swing.JLabel guiSum;
    private org.jdesktop.swingx.JXTable guiTable;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

}
