/*
 *    Geotoolkit - An Open Source Java GIS Toolkit
 *    http://www.geotoolkit.org
 *
 *    (C) 2007 - 2008, Open Source Geospatial Foundation (OSGeo)
 *    (C) 2008 - 2009, Johann Sorel
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.geotoolkit.gui.swing.filter;

import java.util.Collection;
import java.util.Iterator;
import java.util.Vector;

import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import org.geotools.filter.text.cql2.CQL;
import org.geotools.filter.text.cql2.CQLException;
import org.geotoolkit.gui.swing.resource.IconBundle;
import org.geotoolkit.gui.swing.misc.FilterToCQL;
import org.geotoolkit.gui.swing.misc.FilterToCQLException;
import org.geotoolkit.gui.swing.resource.MessageBundle;
import org.geotoolkit.map.FeatureMapLayer;
import org.geotoolkit.map.MapLayer;
import org.opengis.feature.type.PropertyDescriptor;
import org.opengis.filter.Filter;

/**
 * CQL filter panel
 * 
 * @author Johann Sorel (Puzzle-GIS)
 */
public class JCQLFilterPanel extends javax.swing.JPanel implements FilterPanel{

    private Filter filter = null;
    private MapLayer layer;

    private final ListSelectionListener listListener = new ListSelectionListener() {

        @Override
            public void valueChanged(ListSelectionEvent e) {
            final JList model = (JList) e.getSource();
            Object value = model.getSelectedValue();
            if(value != null){
                append(value.toString());
            }

            }
    };

    /** Creates new form JCQLPropertyPanel */
    public JCQLFilterPanel() {
        initComponents();

        lst_basic.addListSelectionListener(listListener);
        lst_gis.addListSelectionListener(listListener);
        lst_field.addListSelectionListener(listListener);
        
//        lst_basic.addListSelectionListener(new ListSelectionListener() {
//
//            public void valueChanged(ListSelectionEvent e) {
//                Object value = lst_basic.getSelectedValue();
//                append(value.toString());
//            }
//        });
//
//        lst_gis.addListSelectionListener(new ListSelectionListener() {
//
//            public void valueChanged(ListSelectionEvent e) {
//                Object value = lst_gis.getSelectedValue();
//                append(value.toString());
//            }
//        });
//
//        lst_field.addListSelectionListener(new ListSelectionListener() {
//
//            public void valueChanged(ListSelectionEvent e) {
//                Object value = lst_field.getSelectedValue();
//                append(value.toString());
//            }
//        });

    }

    private void append(String val) {
        if (!txt_cql.getText().endsWith(val)) {

            if (!txt_cql.getText().endsWith(" ") && txt_cql.getText().length() > 0) {
                txt_cql.append(" ");
            }
            txt_cql.append(val);
        }
    }

    private Filter verifyQuery(String str) {

        try {
            Filter flt = CQL.toFilter(str);
            txt_error.setText(" ");
            return flt;
        } catch (CQLException e) {
            txt_error.setText(MessageBundle.getString("property_cql_error"));
            return null;
        }
    }

    private void parse(Filter filter) {

        FilterToCQL visitor = new FilterToCQL();

        try {
            txt_cql.setText(visitor.encodeToString(layer.getQuery().getFilter()));
        } catch (FilterToCQLException e) {
            e.printStackTrace();
        }

    }

    private void parse(MapLayer ly) {
        
        if(layer instanceof FeatureMapLayer){
            FeatureMapLayer layer = (FeatureMapLayer) ly;
        lst_field.removeAll();

        Collection<PropertyDescriptor> col = layer.getFeatureSource().getSchema().getDescriptors();
        Iterator<PropertyDescriptor> it = col.iterator();

        PropertyDescriptor desc;
        Vector<String> vec = new Vector<String>();
        while (it.hasNext()) {
            desc = it.next();
            vec.add(desc.getName().toString());
        }


            lst_field.removeListSelectionListener(listListener);
        lst_field.setListData(vec);
            lst_field.addListSelectionListener(listListener);
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        txt_cql = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_field = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_gis = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst_basic = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_error = new javax.swing.JLabel();

        txt_cql.setColumns(20);
        txt_cql.setRows(5);
        jScrollPane4.setViewportView(txt_cql);

        lst_field.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lst_field);

        lst_gis.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "CONTAINS(<ATTR1>,<POINT(1 2)>)", "CROSS(<ATTR1>,<LINESTRING(1 2, 10 15)>)", "INTERSECT(<ATTR1>,<GEOMETRYCOLLECTION (POINT (10 10),POINT (30 30),LINESTRING (15 15, 20 20))> )", "BBOX(<ATTR1>,<10>,<20>,<30>,<40>)", "DWITHIN(<ATTR1>, <POINT(1 2)>, <10>, <kilometers>)" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lst_gis.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lst_gis);

        lst_basic.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "AND", "OR", "=", "<", "<=", ">", ">=", "BETWEEN", "LIKE", "NOT LIKE", "IS NULL", "IS NOT NULL", "EXISTS", "DOES-NOT-EXIST", "BEFORE", "AFTER", "DURING" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lst_basic.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(lst_basic);

        jLabel2.setText(MessageBundle.getString("property_cql_basic")); // NOI18N

        jLabel1.setText(MessageBundle.getString("property_cql_advance")); // NOI18N

        jLabel4.setText(MessageBundle.getString("property_cql_field")); // NOI18N

        txt_error.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                    .addComponent(txt_error, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_error)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList lst_basic;
    private javax.swing.JList lst_field;
    private javax.swing.JList lst_gis;
    private javax.swing.JTextArea txt_cql;
    private javax.swing.JLabel txt_error;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void setFilter(Filter filter) {
        if (filter == null) {
            throw new NullPointerException();
        }

        this.filter = filter;
        parse(filter);
    }

    @Override
    public Filter getFilter() {
        Filter flt = verifyQuery(txt_cql.getText());

        if (flt == null) {
            flt = Filter.INCLUDE;
        }
        filter = flt;        
        return filter;
    }

    @Override
    public void setLayer(MapLayer layer) {

        if (layer == null) {
            throw new NullPointerException();
        }

        this.layer = layer;
        parse(layer);
    }

    @Override
    public MapLayer getLayer() {
        return layer;
    }
 
        
    public String getTitle() {
        return MessageBundle.getString("property_cql_filter");
    }

    public ImageIcon getIcon() {
        return IconBundle.getInstance().getIcon("16_filter_cql");
    }

    public String getToolTip() {
        return null;
    }
       
    @Override
    public JComponent getComponent() {
        return this;
    }
}
