

package org.geotoolkit.gui.swing.go.control;

import java.util.ArrayList;
import java.util.List;
import javax.measure.unit.NonSI;
import javax.measure.unit.SI;
import javax.measure.unit.Unit;
import org.geotoolkit.gui.swing.go.GoMap2D;
import org.geotoolkit.gui.swing.go.decoration.JNorthArrowDecoration;
import org.geotoolkit.gui.swing.go.decoration.JScaleBarDecoration;
import org.geotoolkit.gui.swing.map.map2d.decoration.MapDecoration;
import org.geotoolkit.gui.swing.resource.MessageBundle;
import org.jdesktop.swingx.combobox.ListComboBoxModel;

/**
 *
 * @author Johann Sorel (Puzzle-GIS)
 */
public class JConfigDialog extends javax.swing.JDialog {

    private final GoMap2D map;

    /** Creates new form JConfigDialog */
    public JConfigDialog(java.awt.Frame parent,GoMap2D map) {
        super(parent, true);
        this.map = map;
        initComponents();

        guiNorthActivate.setSelected(getNorthDecoration() != null);

        JScaleBarDecoration deco = getScaleDecoration();
        if(deco != null){
            guiScaleActivate.setSelected(true);
            guiUnit.setSelectedItem(deco.getUnit());
        }else{
            guiScaleActivate.setSelected(false);
        }
        

        List<Unit> list = new ArrayList<Unit>();
        list.add(SI.METER);
        list.add(SI.KILOMETER);
        list.add(NonSI.FOOT);
        list.add(NonSI.MILE);

        guiUnit.setModel(new ListComboBoxModel(list));

    }

    private JNorthArrowDecoration getNorthDecoration(){
        for(MapDecoration deco : map.getDecorations()){
            if(deco instanceof JNorthArrowDecoration){
                return (JNorthArrowDecoration) deco;
            }
        }
        return null;
    }

    private JScaleBarDecoration getScaleDecoration(){
        for(MapDecoration deco : map.getDecorations()){
            if(deco instanceof JScaleBarDecoration){
                return (JScaleBarDecoration) deco;
            }
        }
        return null;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        guiScaleActivate = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        guiUnit = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        guiNorthActivate = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        guiScaleActivate.setText(MessageBundle.getString("map_control_activate")); // NOI18N
        guiScaleActivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiScaleActivateActionPerformed(evt);
            }
        });

        jLabel1.setText(MessageBundle.getString("map_control_unit")); // NOI18N

        guiUnit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                guiUnitItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guiScaleActivate)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guiScaleActivate)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(guiUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Scale bar", jPanel2);

        guiNorthActivate.setText(MessageBundle.getString("map_control_activate")); // NOI18N
        guiNorthActivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiNorthActivateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guiNorthActivate)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guiNorthActivate)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("North arrow", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("ScaleBar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guiNorthActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiNorthActivateActionPerformed
        if(guiNorthActivate.isSelected()){
            if(getNorthDecoration() == null)map.addDecoration(new JNorthArrowDecoration());
        }else{
            map.removeDecoration(getNorthDecoration());
        }
    }//GEN-LAST:event_guiNorthActivateActionPerformed

    private void guiScaleActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiScaleActivateActionPerformed
        if(guiScaleActivate.isSelected()){
            if(getScaleDecoration() == null)map.addDecoration(new JScaleBarDecoration());
        }else{
            map.removeDecoration(getScaleDecoration());
        }
    }//GEN-LAST:event_guiScaleActivateActionPerformed

    private void guiUnitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_guiUnitItemStateChanged
        JScaleBarDecoration deco = getScaleDecoration();
        if(deco != null){
            deco.setUnit((Unit) guiUnit.getSelectedItem());
        }

    }//GEN-LAST:event_guiUnitItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox guiNorthActivate;
    private javax.swing.JCheckBox guiScaleActivate;
    private javax.swing.JComboBox guiUnit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
