/*
 *    Geotoolkit - An Open Source Java GIS Toolkit
 *    http://www.geotoolkit.org
 *
 *    (C) 2008 - 2009, Johann Sorel
 *    (C) 2011 Geomatys
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.geotoolkit.gui.swing.propertyedit.styleproperty.simple;

import org.geotoolkit.gui.swing.style.JBankView;
import org.geotoolkit.gui.swing.style.StyleBank;
import org.geotoolkit.gui.swing.style.StyleElementEditor;
import org.geotoolkit.map.MapLayer;
import org.opengis.style.ExternalGraphic;
import org.opengis.style.GraphicalSymbol;
import org.opengis.style.Mark;

/**
 * Graphical symbol editor
 * @author Fabien Rétif
 */
public class JGraphicalSymbolPane extends StyleElementEditor<GraphicalSymbol> {

    private MapLayer layer = null;  
    private StyleBank model = StyleBank.getInstance();    
    private JBankView<Mark> guiMarkPane = null;

    
    /** 
     * Creates new form JGraphicalSymbolPane 
     */
    public JGraphicalSymbolPane() {
        super(GraphicalSymbol.class);
        initComponents();  
        
        guiMarkPane = new JBankView<Mark>(Mark.class);
        guiMarkPane.setCandidates( model.getCandidates(new StyleBank.ByClassComparator(new Class[] {Mark.class}))); 
        
        jTabbedPane1.addTab("Formes prédéfinies", guiMarkPane);
        
    }

    /**
     * {@inheritDoc }
     */
    @Override
    public void setLayer(final MapLayer layer) {
        this.layer = layer;   
        guiExternalGraphicPane.setLayer(layer);
        guiMarkPane.setLayer(layer);
    }

    /**
     * {@inheritDoc }
     */
    @Override
    public MapLayer getLayer(){
        return layer;
    }
    
    /**
     * {@inheritDoc }
     * This method parses a GraphicalSymbol object and sets up all graphic components in order to display it. If the object can not be parse, we display a square mark
     */
    @Override
    public void parse(final GraphicalSymbol graphicalSymbol) {
        
        if (graphicalSymbol != null) { 
            
             if (graphicalSymbol instanceof Mark)
                {
                    jTabbedPane1.setSelectedComponent(guiMarkPane);
                    guiMarkPane.parse((Mark)graphicalSymbol);
                }                
                else if (graphicalSymbol instanceof ExternalGraphic)
                {
                    jTabbedPane1.setSelectedComponent(guiExternalGraphicPane);
                    guiExternalGraphicPane.parse((ExternalGraphic)graphicalSymbol);     
                }                    
             else
                {
                    jTabbedPane1.setSelectedComponent(guiMarkPane);
                    guiMarkPane.parse(getStyleFactory().getSquareMark());
                }
                
        }
    }

    /**
     * {@inheritDoc }
     * This method creates a Graphical Symbol object from the user selection.
     */
    @Override
    public GraphicalSymbol create() {        
        
        GraphicalSymbol symbol = guiExternalGraphicPane.create();
        
        if(symbol == null) {
            symbol = guiMarkPane.create();
        }
        
        return symbol;
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        guiExternalGraphicPane = new JExternalGraphicPane();

        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addTab("Image", guiExternalGraphicPane);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:

        // To avoid NullPointerException at the startup
        if (guiMarkPane != null) {
            guiMarkPane.parse(null);
            guiExternalGraphicPane.parse(null);
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.geotoolkit.gui.swing.propertyedit.styleproperty.simple.JExternalGraphicPane guiExternalGraphicPane;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
