/*
 *    Geotoolkit - An Open Source Java GIS Toolkit
 *    http://www.geotoolkit.org
 *
 *    (C) 2008 - 2009, Johann Sorel
 *    (C) 2011 Geomatys
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.geotoolkit.gui.swing.propertyedit.styleproperty.simple;

import javax.swing.JOptionPane;
import org.geotoolkit.gui.swing.style.StyleElementEditor;
import org.geotoolkit.map.MapLayer;
import org.opengis.style.GraphicalSymbol;

/**
 * Graphical symbol controller editor
 * @author Fabien Rétif
 */
public class JGraphicSymbolControlPane extends StyleElementEditor<GraphicalSymbol> {

    private MapLayer layer = null;    
    private JGraphicalSymbolPane paneGraphicalSymbolChooser = new JGraphicalSymbolPane();

    /** 
     * Creates new form JGraphicSymbolControlPane
     */
    public JGraphicSymbolControlPane() {
        super(GraphicalSymbol.class);
        initComponents();        
    }

    /**
     * {@inheritDoc }
     */
    @Override
    public void setLayer(final MapLayer layer) {
        this.layer = layer;     
        paneGraphicalSymbolChooser.setLayer(layer);
    }

    /**
     * {@inheritDoc }
     */
    @Override
    public MapLayer getLayer(){
        return layer;
    }
    
    /**
     * {@inheritDoc }
     */
    @Override
    public void parse(final GraphicalSymbol graphicalSymbol) {
        
        if (graphicalSymbol != null) {

            guiMarkLabel.parse(graphicalSymbol);            
            paneGraphicalSymbolChooser.parse(graphicalSymbol);            
        }
    }

    /**
     * {@inheritDoc }
     */
    @Override
    public GraphicalSymbol create() {
        return paneGraphicalSymbolChooser.create();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guiMarkButton = new javax.swing.JButton();
        guiMarkLabel = new org.geotoolkit.gui.swing.style.JPreview();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(250, 30));
        setLayout(new java.awt.BorderLayout());

        guiMarkButton.setText("Changer");
        guiMarkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiMarkButtonActionPerformed(evt);
            }
        });
        add(guiMarkButton, java.awt.BorderLayout.EAST);

        guiMarkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiMarkLabelMouseClicked(evt);
            }
        });
        add(guiMarkLabel, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

    private void guiMarkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiMarkButtonActionPerformed
        // TODO add your handling code here:        
        JOptionPane.showMessageDialog(null,paneGraphicalSymbolChooser,"",JOptionPane.PLAIN_MESSAGE);
        firePropertyChange(PROPERTY_TARGET, null, create());
        parse(create());
        
    }//GEN-LAST:event_guiMarkButtonActionPerformed

    private void guiMarkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiMarkLabelMouseClicked
        // TODO add your handling code here:        
        JOptionPane.showMessageDialog(null,paneGraphicalSymbolChooser,"",JOptionPane.PLAIN_MESSAGE);
        firePropertyChange(PROPERTY_TARGET, null, create());
        parse(create());
    }//GEN-LAST:event_guiMarkLabelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guiMarkButton;
    private org.geotoolkit.gui.swing.style.JPreview guiMarkLabel;
    // End of variables declaration//GEN-END:variables
   
}
