/*
 *    Geotoolkit - An Open Source Java GIS Toolkit
 *    http://www.geotoolkit.org
 *
 *    (C) 2008 - 2009, Johann Sorel
 *    (C) 2011 Geomatys
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.geotoolkit.gui.swing.propertyedit.styleproperty.simple;

import javax.swing.JOptionPane;
import org.geotoolkit.gui.swing.style.StyleElementEditor;
import org.geotoolkit.map.MapLayer;
import org.opengis.style.Stroke;

/**
 * Stroke controller editor
 * @author Fabien Rétif
 */
public class JStrokeControlPane extends StyleElementEditor<Stroke> {

    private MapLayer layer = null;    
    private JStrokePane paneStrokeChooser = new JStrokePane();

    /**
     * Creates new form JStrokeControlPane
     */
    public JStrokeControlPane() {
        super(Stroke.class);
        initComponents();   
    }     
    
     /**
     * {@inheritDoc }
     */
    @Override
    public void setLayer(final MapLayer layer) {
        this.layer = layer;   
        paneStrokeChooser.setLayer(layer);
    }

    /**
     * {@inheritDoc }
     */
    @Override
    public MapLayer getLayer(){
        return layer;       
    }
    
    /**
     * {@inheritDoc }
     */
    @Override
    public void parse(final Stroke stroke) {
       
        if (stroke != null) {
                        
            //Create the icon image            
            guiStrokeLabel.parse(stroke);   
            // Set the tool pane
            paneStrokeChooser.parse(stroke);           
        }
    }

    /**
     * {@inheritDoc }
     */
    @Override
    public Stroke create() {
        return paneStrokeChooser.create();
    }
    
    public void setActive(Boolean bool)
    {        
        guiStrokeButton.setEnabled(bool);
        guiStrokeLabel.setVisible(bool);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guiStrokeButton = new javax.swing.JButton();
        guiStrokeLabel = new org.geotoolkit.gui.swing.style.JPreview();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(250, 30));
        setLayout(new java.awt.BorderLayout());

        guiStrokeButton.setText("Changer");
        guiStrokeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiStrokeButtonActionPerformed(evt);
            }
        });
        add(guiStrokeButton, java.awt.BorderLayout.EAST);

        guiStrokeLabel.setPreferredSize(new java.awt.Dimension(32, 32));
        guiStrokeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiStrokeLabelMouseClicked(evt);
            }
        });
        add(guiStrokeLabel, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

    private void guiStrokeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiStrokeButtonActionPerformed
        // TODO add your handling code here:        
        JOptionPane.showMessageDialog(null,paneStrokeChooser,"",JOptionPane.PLAIN_MESSAGE);   
        firePropertyChange(PROPERTY_TARGET, null, create());
        parse(create());
    }//GEN-LAST:event_guiStrokeButtonActionPerformed

    private void guiStrokeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiStrokeLabelMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,paneStrokeChooser,"",JOptionPane.PLAIN_MESSAGE);   
        firePropertyChange(PROPERTY_TARGET, null, create());
        parse(create());
    }//GEN-LAST:event_guiStrokeLabelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guiStrokeButton;
    private org.geotoolkit.gui.swing.style.JPreview guiStrokeLabel;
    // End of variables declaration//GEN-END:variables
}
