//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.21 at 12:27:36 PM CEST 
//


package org.geotoolkit.internal.jaxb.v110.se;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LabelPlacementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LabelPlacementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.opengis.net/se}PointPlacement"/>
 *         &lt;element ref="{http://www.opengis.net/se}LinePlacement"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LabelPlacementType", propOrder = {
    "pointPlacement",
    "linePlacement"
})
public class LabelPlacementType {

    @XmlElement(name = "PointPlacement")
    protected PointPlacementType pointPlacement;
    @XmlElement(name = "LinePlacement")
    protected LinePlacementType linePlacement;

    /**
     * Gets the value of the pointPlacement property.
     * 
     * @return
     *     possible object is
     *     {@link PointPlacementType }
     *     
     */
    public PointPlacementType getPointPlacement() {
        return pointPlacement;
    }

    /**
     * Sets the value of the pointPlacement property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointPlacementType }
     *     
     */
    public void setPointPlacement(PointPlacementType value) {
        this.pointPlacement = value;
    }

    /**
     * Gets the value of the linePlacement property.
     * 
     * @return
     *     possible object is
     *     {@link LinePlacementType }
     *     
     */
    public LinePlacementType getLinePlacement() {
        return linePlacement;
    }

    /**
     * Sets the value of the linePlacement property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinePlacementType }
     *     
     */
    public void setLinePlacement(LinePlacementType value) {
        this.linePlacement = value;
    }

}
