/*
 *    Geotoolkit - An Open Source Java GIS Toolkit
 *    http://www.geotoolkit.org
 *
 *    (C) 2008, Open Source Geospatial Foundation (OSGeo)
 *    (C) 2008 - 2009, Johann Sorel
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.geotoolkit.gui.swing.go.decoration;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JSlider;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.geotoolkit.gui.swing.go.GoMap2D;
import org.geotoolkit.gui.swing.map.map2d.Map2D;
import org.geotoolkit.gui.swing.map.map2d.decoration.MapDecoration;

/**
 *
 * @author sorel
 */
public class QuadDNavigationDecoration extends JPanel implements MapDecoration{

    private GoMap2D map = null;

    /** Creates new form QuadDNavigationDecoration */
    public QuadDNavigationDecoration() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guiSldDeapht = new JSlider();

        setOpaque(false);

        guiSldDeapht.setMaximum(1000);
        guiSldDeapht.setOrientation(JSlider.VERTICAL);
        guiSldDeapht.setValue(0);
        guiSldDeapht.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                guiSldDeaphtStateChanged(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addComponent(guiSldDeapht, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guiSldDeapht, GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guiSldDeaphtStateChanged(ChangeEvent evt) {//GEN-FIRST:event_guiSldDeaphtStateChanged

        if(map != null){
//            map.getCanvas().getController().setVerticalRange(guiSldDeapht.getValue(), guiSldDeapht.getValue());
        }
    }//GEN-LAST:event_guiSldDeaphtStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JSlider guiSldDeapht;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refresh() {
    }

    @Override
    public void dispose() {
    }

    @Override
    public void setMap2D(Map2D map) {

        if(map instanceof GoMap2D){
            this.map = (GoMap2D) map;
        }
    }

    @Override
    public Map2D getMap2D() {
        return map;
    }

    @Override
    public JComponent geComponent() {
        return this;
    }

}
