/*
 *    Geotoolkit.org - An Open Source Java GIS Toolkit
 *    http://www.geotoolkit.org
 *
 *    (C) 2005-2011, Open Source Geospatial Foundation (OSGeo)
 *    (C) 2010-2011, Geomatys
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */

#ifndef _org_geotoolkit_openoffice_XReferencing_
#define _org_geotoolkit_openoffice_XReferencing_

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/beans/XPropertySet.idl>
#include <com/sun/star/sheet/AddIn.idl>


module org {
  module geotoolkit {
    module openoffice {
      /// Methods from the org.geotoolkit.referencing package to make available to OpenOffice.
      interface XReferencing : com::sun::star::uno::XInterface {
        /// Converts text in degrees-minutes-seconds to an angle in decimal degrees.
        double getValueAngle(
          [in] com::sun::star::beans::XPropertySet xOptions,
          /// The text to be converted to an angle.
          [in] string text,
          /// The text that describes the format (example: "D MM.m'").
          [in] any pattern
        ) raises (com::sun::star::lang::IllegalArgumentException);

        /// Converts an angle to text according to a given format.
        string getTextAngle(
          [in] com::sun::star::beans::XPropertySet xOptions,
          /// The angle value (in decimal degrees) to be converted.
          [in] double value,
          /// The text that describes the format (example: "D MM.m'").
          [in] any pattern
        ) raises (com::sun::star::lang::IllegalArgumentException);

        /// Converts a longitude to text according to a given format.
        string getTextLongitude(
          [in] com::sun::star::beans::XPropertySet xOptions,
          /// The longitude value (in decimal degrees) to be converted.
          [in] double value,
          /// The text that describes the format (example: "D MM.m'").
          [in] any pattern
        ) raises (com::sun::star::lang::IllegalArgumentException);

        /// Converts a latitude to text according to a given format.
        string getTextLatitude(
          [in] com::sun::star::beans::XPropertySet xOptions,
          /// The latitude value (in decimal degrees) to be converted.
          [in] double value,
          /// The text that describes the format (example: "D MM.m'").
          [in] any pattern
        ) raises (com::sun::star::lang::IllegalArgumentException);

        /// Computes the orthodromic distance and azimuth between two coordinates.
        sequence< sequence< double > > getOrthodromicDistance(
          [in] com::sun::star::beans::XPropertySet xOptions,
          /// The source positions.
          [in] sequence< sequence< double > > source,
          /// The target positions.
          [in] sequence< sequence< double > > target,
          /// Authority code of the coordinate reference system.
          [in] any CRS
        );

        /// Computes the coordinates after a displacement of the specified distance.
        sequence< sequence< double > > getOrthodromicForward(
          [in] com::sun::star::beans::XPropertySet xOptions,
          /// The source positions.
          [in] sequence< sequence< double > > source,
          /// The distance and azimuth.
          [in] sequence< sequence< double > > displacement,
          /// Authority code of the coordinate reference system.
          [in] any CRS
        );
      };

      /*
       * Exported interfaces:
       * This is where we put all interfaces that this service exports.
       */
      service Referencing {
        interface XReferencing;

        /*
         * Necessary base service.
         * All add-ins must implement this service
         */
        service com::sun::star::sheet::AddIn;
      };
    };
  };
};

#endif
