build:
  # Mainly check project sanity by installing all components and running unit tests.
  # It also serve as main job for cache update.
  #
  # For now, disable it for sis-migration because:
  # 1. We would need to build GeoAPI / SIS beforehand
  # 2. We have to be careful with maven local repository caching, that would be polluted with GeoAPI and SIS snapshots
  # 3. Anyway, dependence upon unstable libraries is a bad idea. If not avoidable, we should use submodules to ease the maintainance
  except:
    refs:
      - sis-migration
  extends: .update-cache
  stage: build
  script:
    - mvn clean install -s $MAVEN_SETTINGS
    - mvn jacoco:report-aggregate
    - mvn javadoc:jar
  artifacts:
    paths:
      - "target/"
      - "*/target/"
    # We want to get test reports even on failure, to quickly find problems
    when: always
    reports:
      junit: "*/target/surefire-reports/TEST-*.xml"
      # TODO: uncomment once our Gitlab instance support Jacoco instance (requires 17.3 with experimental flag)
      # coverage_report:
      #   coverage_format: jacoco
      #   path: "target/site/jacoco-aggregate/jacoco.xml"
